#!/bin/bash
#-----------------------
# Testing cinder-daemons
#-----------------------
set -e
DAEMONS=('apache2' 'cinder-scheduler')

if grep -qE "^(sql_)?connection.*sqlite.*" /etc/cinder/cinder.conf
then
    su -s /bin/sh -c 'cinder-manage db sync' cinder
fi

for daemon in "${DAEMONS[@]}"; do
    systemctl restart $daemon
done

for daemon in "${DAEMONS[@]}"; do
    if pidof -x $daemon > /dev/null; then
        echo "OK"
    else
        echo "ERROR: ${daemon} IS NOT RUNNING"
        exit 1
    fi
done
