#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/cinder-backup cinder-backup /usr/bin/python2-cinder-backup 200
	update-alternatives --install /usr/bin/cinder-manage cinder-manage /usr/bin/python2-cinder-manage 200
	update-alternatives --install /usr/bin/cinder-rootwrap cinder-rootwrap /usr/bin/python2-cinder-rootwrap 200
	update-alternatives --install /usr/bin/cinder-rtstool cinder-rtstool /usr/bin/python2-cinder-rtstool 200
	update-alternatives --install /usr/bin/cinder-scheduler cinder-scheduler /usr/bin/python2-cinder-scheduler 200
	update-alternatives --install /usr/bin/cinder-volume cinder-volume /usr/bin/python2-cinder-volume 200
	update-alternatives --install /usr/bin/cinder-volume-usage-audit cinder-volume-usage-audit /usr/bin/python2-cinder-volume-usage-audit 200
	update-alternatives --install /usr/bin/cinder-wsgi cinder-wsgi /usr/bin/python2-cinder-wsgi 200
fi

#DEBHELPER#

exit 0
